[INFO][0][<module>] Darwin MT-202641 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64
[INFO][0][<module>] /usr/local/lib/python3.9/site-packages/ILAMB (2.6)
[INFO][0][<module>] /usr/local/lib/python3.9/site-packages/numpy (1.20.0)
[INFO][0][<module>] /usr/local/lib/python3.9/site-packages/matplotlib (3.4.2)
[INFO][0][<module>] /usr/local/lib/python3.9/site-packages/netCDF4 (1.5.7)
[INFO][0][<module>] /usr/local/lib/python3.9/site-packages/cf_units (3.0.1)
[INFO][0][<module>] /usr/local/lib/python3.9/site-packages/sympy (1.8)
[INFO][0][<module>] /usr/local/lib/python3.9/site-packages/mpi4py (3.0.3)
[INFO][0][<module>] 2021-08-03 11:58:30.015588
[INFO][0][confront][GrossPrimaryProductivity/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][confront][GrossPrimaryProductivity/FLUXNET2015][EnsembleCMIP6] Success
[INFO][0][confront][GrossPrimaryProductivity/FLUXNET2015][CliMA] Success
[INFO][0][confront][GrossPrimaryProductivity/FLUXCOM][EnsembleCMIP5] Success
[INFO][0][confront][GrossPrimaryProductivity/FLUXCOM][EnsembleCMIP6] Success
[INFO][0][confront][GrossPrimaryProductivity/FLUXCOM][CliMA] Success
[INFO][0][confront][SurfaceAirTemperature/CRU4.02][EnsembleCMIP5] Success
[INFO][0][confront][SurfaceAirTemperature/CRU4.02][EnsembleCMIP6] Success
[DEBUG][0][extractTimeSeries][CliMA] Could not find [tas] in the model results
[DEBUG][0][WorkConfront][SurfaceAirTemperature/CRU4.02][CliMA]
Traceback (most recent call last):
  File "/usr/local/bin/ilamb-run", line 384, in WorkConfront
    c.confront(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 350, in confront
    obs,mod = self.stageData(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 297, in stageData
    mod = m.extractTimeSeries(self.variable,
  File "/usr/local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 326, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][confront][SurfaceAirTemperature/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][confront][SurfaceAirTemperature/FLUXNET2015][EnsembleCMIP6] Success
[DEBUG][0][extractTimeSeries][CliMA] Could not find [tas] in the model results
[DEBUG][0][WorkConfront][SurfaceAirTemperature/FLUXNET2015][CliMA]
Traceback (most recent call last):
  File "/usr/local/bin/ilamb-run", line 384, in WorkConfront
    c.confront(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 350, in confront
    obs,mod = self.stageData(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 297, in stageData
    mod = m.extractTimeSeries(self.variable,
  File "/usr/local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 326, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][confront][Precipitation/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][confront][Precipitation/FLUXNET2015][EnsembleCMIP6] Success
[DEBUG][0][extractTimeSeries][CliMA] Could not find [pr] in the model results
[DEBUG][0][WorkConfront][Precipitation/FLUXNET2015][CliMA]
Traceback (most recent call last):
  File "/usr/local/bin/ilamb-run", line 384, in WorkConfront
    c.confront(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 350, in confront
    obs,mod = self.stageData(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 297, in stageData
    mod = m.extractTimeSeries(self.variable,
  File "/usr/local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 326, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][confront][Precipitation/GPCPv2.3][EnsembleCMIP5] Success
[INFO][0][confront][Precipitation/GPCPv2.3][EnsembleCMIP6] Success
[DEBUG][0][extractTimeSeries][CliMA] Could not find [pr] in the model results
[DEBUG][0][WorkConfront][Precipitation/GPCPv2.3][CliMA]
Traceback (most recent call last):
  File "/usr/local/bin/ilamb-run", line 384, in WorkConfront
    c.confront(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 350, in confront
    obs,mod = self.stageData(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 297, in stageData
    mod = m.extractTimeSeries(self.variable,
  File "/usr/local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 326, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][confront][SurfaceDownwardSWRadiation/CERESed4.1][EnsembleCMIP5] Success
[INFO][0][confront][SurfaceDownwardSWRadiation/CERESed4.1][EnsembleCMIP6] Success
[DEBUG][0][extractTimeSeries][CliMA] Could not find [rsds] in the model results
[DEBUG][0][WorkConfront][SurfaceDownwardSWRadiation/CERESed4.1][CliMA]
Traceback (most recent call last):
  File "/usr/local/bin/ilamb-run", line 384, in WorkConfront
    c.confront(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 350, in confront
    obs,mod = self.stageData(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 297, in stageData
    mod = m.extractTimeSeries(self.variable,
  File "/usr/local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 326, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][confront][SurfaceDownwardSWRadiation/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][confront][SurfaceDownwardSWRadiation/FLUXNET2015][EnsembleCMIP6] Success
[DEBUG][0][extractTimeSeries][CliMA] Could not find [rsds] in the model results
[DEBUG][0][WorkConfront][SurfaceDownwardSWRadiation/FLUXNET2015][CliMA]
Traceback (most recent call last):
  File "/usr/local/bin/ilamb-run", line 384, in WorkConfront
    c.confront(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 350, in confront
    obs,mod = self.stageData(m)
  File "/usr/local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 297, in stageData
    mod = m.extractTimeSeries(self.variable,
  File "/usr/local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 326, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][modelPlots][GrossPrimaryProductivity/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/FLUXNET2015][EnsembleCMIP6] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/FLUXNET2015][CliMA] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/FLUXCOM][EnsembleCMIP5] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/FLUXCOM][EnsembleCMIP6] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/FLUXCOM][CliMA] Success
[INFO][0][modelPlots][SurfaceAirTemperature/CRU4.02][EnsembleCMIP5] Success
[INFO][0][modelPlots][SurfaceAirTemperature/CRU4.02][EnsembleCMIP6] Success
[INFO][0][modelPlots][SurfaceAirTemperature/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][modelPlots][SurfaceAirTemperature/FLUXNET2015][EnsembleCMIP6] Success
[INFO][0][modelPlots][Precipitation/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][modelPlots][Precipitation/FLUXNET2015][EnsembleCMIP6] Success
[INFO][0][modelPlots][Precipitation/GPCPv2.3][EnsembleCMIP5] Success
[INFO][0][modelPlots][Precipitation/GPCPv2.3][EnsembleCMIP6] Success
[INFO][0][modelPlots][SurfaceDownwardSWRadiation/CERESed4.1][EnsembleCMIP5] Success
[INFO][0][modelPlots][SurfaceDownwardSWRadiation/CERESed4.1][EnsembleCMIP6] Success
[INFO][0][modelPlots][SurfaceDownwardSWRadiation/FLUXNET2015][EnsembleCMIP5] Success
[INFO][0][modelPlots][SurfaceDownwardSWRadiation/FLUXNET2015][EnsembleCMIP6] Success
[INFO][0][<module>][total time] 816.8 s
